baseurl = "https://blog.lol320.work/"
languageCode = "ja"
title = "Hyphen-Seven"
disqusShortname = "hyphen7blog"
theme = "angels-ladder"

[Params]
subtitle = "Learn and Be curious."
twitter = "https://twitter.com/"
github = "https://github.com/hyphen7"
showsRSS = true
profile = "/images/bakeneko.png"
copyright = "Written by Takuma"