baseurl = "https://hyphen7.github.io/"
languageCode = "ja"
title = "Hyphen-Seven"
disqusShortname = "Ba56lloon"
theme = "angels-ladder"

[Params]
subtitle = "Learn and Be curious."
twitter = "https://twitter.com/612kygo"
github = "https://github.com/hyphen7"
showsRSS = true
profile = "/images/bakeneko.png"
copyright = "Written by Ba56lloon"